#!/bin/bash
#blsimu_SRCDIR=./
blsimu_SRCDIR=~/Data/notes/LBCS/blsimu+/
export blsimu_SRCDIR
# issue this exe with program name as
# run drawBmShape
# or just issue
# run
# to use default doprm.
${blsimu_SRCDIR}exe